name: Continuous Integration
on:
  push:
  pull_request:
  schedule:
    - cron: '42 15 * * *'
jobs:
  build:
    name: HHVM ${{matrix.hhvm}} - ${{matrix.os}}
    strategy:
      # Run tests on all OS's and HHVM versions, even if one fails
      fail-fast: false
      matrix:
        os: [ ubuntu , macos ]
        hhvm:
          - '4.80'
          - latest
          - nightly
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - name: foo
        uses: jjergus/hacktest/.github/actions/hack-lint-test@master
        with:
          hhvm: ${{matrix.hhvm}}
      - name: Lint
        run: bin/hhast-lint
      - name: Check for manually modified codegen
        run: vendor/bin/hh-codegen-verify-signatures codegen/
